ALTER TABLE UsuarioR DROP FOREIGN KEY FKUsuarioR673303;
ALTER TABLE Cliente DROP FOREIGN KEY FKCliente479341;
ALTER TABLE Casa DROP FOREIGN KEY FKCasa996939;
ALTER TABLE Administrador DROP FOREIGN KEY FKAdministra965393;
ALTER TABLE Municipio DROP FOREIGN KEY FKMunicipio876975;
ALTER TABLE Inmueble DROP FOREIGN KEY FKInmueble576664;
ALTER TABLE Inmueble DROP FOREIGN KEY FKInmueble287909;
ALTER TABLE Inmueble_Extra DROP FOREIGN KEY FKInmueble_E704924;
ALTER TABLE Inmueble_Extra DROP FOREIGN KEY FKInmueble_E450466;
ALTER TABLE Correo DROP FOREIGN KEY FKCorreo423872;
ALTER TABLE Correo DROP FOREIGN KEY FKCorreo31640;
ALTER TABLE Provincia DROP FOREIGN KEY FKProvincia54408;
ALTER TABLE CodigoPostal DROP FOREIGN KEY FKCodigoPost261095;
ALTER TABLE Inmueble DROP FOREIGN KEY FKInmueble718913;
ALTER TABLE UsuarioR DROP FOREIGN KEY FKUsuarioR246398;
ALTER TABLE Casa DROP FOREIGN KEY FKCasa221567;
ALTER TABLE UsuarioR_Casa DROP FOREIGN KEY FKUsuarioR_C197391;
ALTER TABLE UsuarioR_Casa DROP FOREIGN KEY FKUsuarioR_C321816;
ALTER TABLE Casa DROP FOREIGN KEY FKCasa466581;
ALTER TABLE Correo DROP FOREIGN KEY FKCorreo974623;
ALTER TABLE Foto DROP FOREIGN KEY FKFoto17775;
DROP TABLE IF EXISTS UsuarioR;
DROP TABLE IF EXISTS Usuario;
DROP TABLE IF EXISTS Provincia;
DROP TABLE IF EXISTS Municipio;
DROP TABLE IF EXISTS Mapa;
DROP TABLE IF EXISTS Inmueble;
DROP TABLE IF EXISTS Foto;
DROP TABLE IF EXISTS Extra;
DROP TABLE IF EXISTS Correo;
DROP TABLE IF EXISTS CodigoPostal;
DROP TABLE IF EXISTS Cliente;
DROP TABLE IF EXISTS Casa;
DROP TABLE IF EXISTS Administrador;
DROP TABLE IF EXISTS Inmueble_Extra;
DROP TABLE IF EXISTS UsuarioR_Casa;
CREATE TABLE UsuarioR (Apellidos varchar(255), UsuarioId_Usuario int(11) NOT NULL, CasaInmuebleId_Inmueble int(11), PRIMARY KEY (UsuarioId_Usuario)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Usuario (Id_Usuario int(11) NOT NULL AUTO_INCREMENT, Correo varchar(255), Nombre varchar(255), Contrasenia varchar(255), PRIMARY KEY (Id_Usuario)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Provincia (Id_provincia int(11) NOT NULL AUTO_INCREMENT, CodigoPostalId_CodigoPostal int(11), Provincia varchar(255), PRIMARY KEY (Id_provincia)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Municipio (Id_Municipio int(11) NOT NULL AUTO_INCREMENT, ProvinciaId_provincia int(11), Municipio varchar(255), PRIMARY KEY (Id_Municipio)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Mapa (Id_mapa int(11) NOT NULL AUTO_INCREMENT, Longitud varchar(255), Latitud varchar(255), Url varchar(2000), PRIMARY KEY (Id_mapa)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Inmueble (Id_Inmueble int(11) NOT NULL AUTO_INCREMENT, CodigoPostalId_CodigoPostal int(11), ProvinciaId_provincia int(11), MunicipioId_Municipio int(11), Direccion varchar(1024), PRIMARY KEY (Id_Inmueble)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Foto (Id_foto int(11) NOT NULL AUTO_INCREMENT, CasaInmuebleId_Inmueble int(11), LinkFoto varchar(2000), PRIMARY KEY (Id_foto)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Extra (Id_Extra int(11) NOT NULL AUTO_INCREMENT, NombreExtra varchar(255), Tipo varchar(255), PRIMARY KEY (Id_Extra)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Correo (Id_Correo int(11) NOT NULL AUTO_INCREMENT, CasaInmuebleId_Inmueble int(11), UsuarioId_Usuario2 int(11), UsuarioId_Usuario int(11), Fuente varchar(255), Destinatario varchar(255), Asunto varchar(255), Texto varchar(2048), PRIMARY KEY (Id_Correo)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE CodigoPostal (Id_CodigoPostal int(11) NOT NULL AUTO_INCREMENT, MunicipioId_Municipio int(11), Codigo_postal varchar(255), PRIMARY KEY (Id_CodigoPostal)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Cliente (Direccion varchar(255), CodigoPostal varchar(255) NOT NULL, UsuarioId_Usuario int(11) NOT NULL, PRIMARY KEY (UsuarioId_Usuario)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Casa (Id_casa int(11) NOT NULL, Precio double NOT NULL, Superficie double, Habitaciones int(11) NOT NULL, Banios int(11) NOT NULL, Tipo varchar(255), Estado varchar(255), Accion varchar(255), NumVisitas int(11) NOT NULL, NumFavoritos int(11) NOT NULL, Visible varchar(255), DCorta varchar(255), DLarga varchar(1024), Fecha date, InmuebleId_Inmueble int(11) NOT NULL, ClienteUsuarioId_Usuario int(11), MapaId_mapa int(11), PRIMARY KEY (InmuebleId_Inmueble)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Administrador (UsuarioId_Usuario int(11) NOT NULL, PRIMARY KEY (UsuarioId_Usuario)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Inmueble_Extra (InmuebleId_Inmueble int(11) NOT NULL, ExtraId_Extra int(11) NOT NULL, PRIMARY KEY (InmuebleId_Inmueble, ExtraId_Extra)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE UsuarioR_Casa (UsuarioRUsuarioId_Usuario int(11) NOT NULL, CasaInmuebleId_Inmueble int(11) NOT NULL, PRIMARY KEY (UsuarioRUsuarioId_Usuario, CasaInmuebleId_Inmueble)) ENGINE=InnoDB CHARACTER SET UTF8;
ALTER TABLE UsuarioR ADD INDEX FKUsuarioR673303 (UsuarioId_Usuario), ADD CONSTRAINT FKUsuarioR673303 FOREIGN KEY (UsuarioId_Usuario) REFERENCES Usuario (Id_Usuario);
ALTER TABLE Cliente ADD INDEX FKCliente479341 (UsuarioId_Usuario), ADD CONSTRAINT FKCliente479341 FOREIGN KEY (UsuarioId_Usuario) REFERENCES Usuario (Id_Usuario);
ALTER TABLE Casa ADD INDEX FKCasa996939 (InmuebleId_Inmueble), ADD CONSTRAINT FKCasa996939 FOREIGN KEY (InmuebleId_Inmueble) REFERENCES Inmueble (Id_Inmueble);
ALTER TABLE Administrador ADD INDEX FKAdministra965393 (UsuarioId_Usuario), ADD CONSTRAINT FKAdministra965393 FOREIGN KEY (UsuarioId_Usuario) REFERENCES Usuario (Id_Usuario);
ALTER TABLE Municipio ADD INDEX FKMunicipio876975 (ProvinciaId_provincia), ADD CONSTRAINT FKMunicipio876975 FOREIGN KEY (ProvinciaId_provincia) REFERENCES Provincia (Id_provincia);
ALTER TABLE Inmueble ADD INDEX FKInmueble576664 (MunicipioId_Municipio), ADD CONSTRAINT FKInmueble576664 FOREIGN KEY (MunicipioId_Municipio) REFERENCES Municipio (Id_Municipio);
ALTER TABLE Inmueble ADD INDEX FKInmueble287909 (ProvinciaId_provincia), ADD CONSTRAINT FKInmueble287909 FOREIGN KEY (ProvinciaId_provincia) REFERENCES Provincia (Id_provincia);
ALTER TABLE Inmueble_Extra ADD INDEX FKInmueble_E704924 (InmuebleId_Inmueble), ADD CONSTRAINT FKInmueble_E704924 FOREIGN KEY (InmuebleId_Inmueble) REFERENCES Inmueble (Id_Inmueble);
ALTER TABLE Inmueble_Extra ADD INDEX FKInmueble_E450466 (ExtraId_Extra), ADD CONSTRAINT FKInmueble_E450466 FOREIGN KEY (ExtraId_Extra) REFERENCES Extra (Id_Extra);
ALTER TABLE Correo ADD INDEX FKCorreo423872 (UsuarioId_Usuario), ADD CONSTRAINT FKCorreo423872 FOREIGN KEY (UsuarioId_Usuario) REFERENCES Usuario (Id_Usuario);
ALTER TABLE Correo ADD INDEX FKCorreo31640 (UsuarioId_Usuario2), ADD CONSTRAINT FKCorreo31640 FOREIGN KEY (UsuarioId_Usuario2) REFERENCES Usuario (Id_Usuario);
ALTER TABLE Provincia ADD INDEX FKProvincia54408 (CodigoPostalId_CodigoPostal), ADD CONSTRAINT FKProvincia54408 FOREIGN KEY (CodigoPostalId_CodigoPostal) REFERENCES CodigoPostal (Id_CodigoPostal);
ALTER TABLE CodigoPostal ADD INDEX FKCodigoPost261095 (MunicipioId_Municipio), ADD CONSTRAINT FKCodigoPost261095 FOREIGN KEY (MunicipioId_Municipio) REFERENCES Municipio (Id_Municipio);
ALTER TABLE Inmueble ADD INDEX FKInmueble718913 (CodigoPostalId_CodigoPostal), ADD CONSTRAINT FKInmueble718913 FOREIGN KEY (CodigoPostalId_CodigoPostal) REFERENCES CodigoPostal (Id_CodigoPostal);
ALTER TABLE UsuarioR ADD INDEX FKUsuarioR246398 (CasaInmuebleId_Inmueble), ADD CONSTRAINT FKUsuarioR246398 FOREIGN KEY (CasaInmuebleId_Inmueble) REFERENCES Casa (InmuebleId_Inmueble);
ALTER TABLE Casa ADD INDEX FKCasa221567 (MapaId_mapa), ADD CONSTRAINT FKCasa221567 FOREIGN KEY (MapaId_mapa) REFERENCES Mapa (Id_mapa);
ALTER TABLE UsuarioR_Casa ADD INDEX FKUsuarioR_C197391 (UsuarioRUsuarioId_Usuario), ADD CONSTRAINT FKUsuarioR_C197391 FOREIGN KEY (UsuarioRUsuarioId_Usuario) REFERENCES UsuarioR (UsuarioId_Usuario);
ALTER TABLE UsuarioR_Casa ADD INDEX FKUsuarioR_C321816 (CasaInmuebleId_Inmueble), ADD CONSTRAINT FKUsuarioR_C321816 FOREIGN KEY (CasaInmuebleId_Inmueble) REFERENCES Casa (InmuebleId_Inmueble);
ALTER TABLE Casa ADD INDEX FKCasa466581 (ClienteUsuarioId_Usuario), ADD CONSTRAINT FKCasa466581 FOREIGN KEY (ClienteUsuarioId_Usuario) REFERENCES Cliente (UsuarioId_Usuario);
ALTER TABLE Correo ADD INDEX FKCorreo974623 (CasaInmuebleId_Inmueble), ADD CONSTRAINT FKCorreo974623 FOREIGN KEY (CasaInmuebleId_Inmueble) REFERENCES Casa (InmuebleId_Inmueble);
ALTER TABLE Foto ADD INDEX FKFoto17775 (CasaInmuebleId_Inmueble), ADD CONSTRAINT FKFoto17775 FOREIGN KEY (CasaInmuebleId_Inmueble) REFERENCES Casa (InmuebleId_Inmueble);
